CREATE DATABASE QLDA_DATA
GO
USE QLDA_DATA

DROP DATABASE QLDA_DATA

GO

CREATE TABLE KHACHHANG(
MaKH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TenKH Nvarchar(50) not null,
Sdt char(10),
GioiTinh int,  -- 0 nam 1-- nữ  2-- khác
DiaChi nvarchar(100),
CONSTRAINT check_gioitinh CHECK(GioiTinh IN (0, 1, 2))
)

GO

CREATE TABLE CHUCVU(
MaCV int IDENTITY(1,1) PRIMARY KEY NOT NULL,
TenCV Nvarchar(20)
)
GO
CREATE TABLE NHANVIEN(
MaNV UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaCV int,
TenNV nvarchar(50) NOT NULL,
Sdt char(10),
GioiTinh int,  -- 0 nam 1-- nữ  2-- khác
DiaChi nvarchar(100),
CONSTRAINT check_gioitinh_nv CHECK(GioiTinh IN (0, 1, 2)),
CONSTRAINT fk_nv_cv  FOREIGN KEY (MaCV) REFERENCES  CHUCVU(MaCV)
)
GO

CREATE TABLE DANHMUC(
MaDM int IDENTITY(1,1) PRIMARY KEY,
TenDM Nvarchar(50)
)

GO

CREATE TABLE SANPHAM(
MaSP UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaDM INT,
TenSP NVARCHAR(100) NOT NULL,
GiaNhap NUMERIC(19, 4) NOT NULL,
GiaBan NUMERIC(19,4) NOT NULL,
SoLuong INT NOT NULL
CONSTRAINT sanpham_danhmuc FOREIGN KEY (MaDM) REFERENCES DANHMUC(MaDM)
)
GO
CREATE TABLE NHACUNGCAP(
MaNCC INT IDENTITY(1,1) PRIMARY KEY,
TenNCC NVARCHAR(100) NOT NULL,
Sdt Char(10),
DiaChi nvarchar(255)
)
GO
CREATE TABLE HOADON(
MaHD UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaNV UNIQUEIDENTIFIER,
MaKH UNIQUEIDENTIFIER,
NgayLapHD SMALLDATETIME,
CONSTRAINT hoadon_nhanvien FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
CONSTRAINT hoadon_khachhang FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),

)
GO

CREATE TABLE CHITIETHOADON
(
MaHD UNIQUEIDENTIFIER,
MaSP UNIQUEIDENTIFIER,
SoLuong INT NOT NULL,
DonGia NUMERIC(19,4) NOT NULL,
ThanhTien NUMERIC(19,4) NOT NULL,
CONSTRAINT pk_hoadon PRIMARY KEY CLUSTERED (MaHD, MaSP),
)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT fk_hd_chitiet FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD)
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT fk_sp_chitiet FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)


GO

CREATE TABLE PHIEUNHAPKHO(
MaPhieuNhap UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaNV UNIQUEIDENTIFIER,
MaNCC INT,
NgayLapHD SMALLDATETIME,
CONSTRAINT phieunhap_nhanvien FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
CONSTRAINT phieunhap_ncc FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC),
)

GO

CREATE TABLE CHITIETPHIEUNHAPKHO(
MaPhieuNhap UNIQUEIDENTIFIER,
MaSP UNIQUEIDENTIFIER,
SoLuong INT NOT NULL,
DonGia NUMERIC(19,4) NOT NULL,
ThanhTien NUMERIC(19,4) NOT NULL,
CONSTRAINT pk PRIMARY KEY CLUSTERED (MaPhieuNhap, MaSP),
CONSTRAINT chitietnhap_phieunhap FOREIGN KEY (MaPhieuNhap) REFERENCES PHIEUNHAPKHO(MaPhieuNhap),
CONSTRAINT chitietnhap_sanpham FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),
)
GO
/*
CREATE TABLE PHIEUXUATKHO(
MaPhieuXuat UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MaNV UNIQUEIDENTIFIER,
MaKH UNIQUEIDENTIFIER,
NgayLapHD SMALLDATETIME,
CONSTRAINT phieuxuat_nhanvien FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
CONSTRAINT phieuxuat_khachhang FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
)

GO

CREATE TABLE CHITIETPHIEUXUATKHO(
MaPhieuXuat UNIQUEIDENTIFIER,
MaSP UNIQUEIDENTIFIER,
SoLuong INT NOT NULL,
DonGia NUMERIC(19,4) NOT NULL,
ThanhTien NUMERIC(19,4) NOT NULL,
CONSTRAINT pk_xuat_sp PRIMARY KEY CLUSTERED (MaPhieuXuat, MaSP),
CONSTRAINT chitietxuat_phieuxuat FOREIGN KEY (MaPhieuXuat) REFERENCES PHIEUXUATKHO(MaPhieuXuat),
CONSTRAINT chitietXuat_sanpham FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP),

) */

GO

CREATE TABLE USERNV(
id INT IDENTITY(1,1) PRIMARY KEY,
MaNV UNIQUEIDENTIFIER,
usename varchar(20),
password char(20),
CONSTRAINT fk_nhanvien_user FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
)


SELECT SoLuong FROM SANPHAM WHERE MaSP = 'bdaa2f7a-2b0a-4d92-8d03-d27f3c259328';
SELECT *FROM KHACHHANG;